//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dota2AdvancedDescriptions.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Dota2AdvancedDescriptions.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Appearance.
        /// </summary>
        public static string Appearance {
            get {
                return ResourceManager.GetString("Appearance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cast backswing text format.
        /// </summary>
        public static string CastBackswingTextFormat {
            get {
                return ResourceManager.GetString("CastBackswingTextFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Example: &quot;Cast backswing: {0}&quot; where {0} is the cast backswing duration..
        /// </summary>
        public static string CastBackswingTooltip {
            get {
                return ResourceManager.GetString("CastBackswingTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cast point text format.
        /// </summary>
        public static string CastPointTextFormat {
            get {
                return ResourceManager.GetString("CastPointTextFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Example: &quot;Cast point: {0}&quot; where {0} is the cast point duration..
        /// </summary>
        public static string CastPointTooltip {
            get {
                return ResourceManager.GetString("CastPointTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change path.
        /// </summary>
        public static string ChangePath {
            get {
                return ResourceManager.GetString("ChangePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Developed by Filippo Vigani.
        /// </summary>
        public static string CreditsShort {
            get {
                return ResourceManager.GetString("CreditsShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //Resources file edited with Dota 2 Advanced Descriptions by Filippo Vigani (Veega). https://github.com/VeegaP/Dota2AdvancedDescriptions.
        /// </summary>
        public static string CreditsText {
            get {
                return ResourceManager.GetString("CreditsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text position.
        /// </summary>
        public static string ExtraTextPosition {
            get {
                return ResourceManager.GetString("ExtraTextPosition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Find me on GitHub!.
        /// </summary>
        public static string FindMeOnGitHub {
            get {
                return ResourceManager.GetString("FindMeOnGitHub", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hide values if equal to zero.
        /// </summary>
        public static string HideValuesIfEqualToZero {
            get {
                return ResourceManager.GetString("HideValuesIfEqualToZero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        public static string Language {
            get {
                return ResourceManager.GetString("Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Launch Dota 2.
        /// </summary>
        public static string LaunchDota {
            get {
                return ResourceManager.GetString("LaunchDota", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add every value to a new line.
        /// </summary>
        public static string NewLineAfterText {
            get {
                return ResourceManager.GetString("NewLineAfterText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preview.
        /// </summary>
        public static string Preview {
            get {
                return ResourceManager.GetString("Preview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Go!.
        /// </summary>
        public static string PublishResources {
            get {
                return ResourceManager.GetString("PublishResources", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset.
        /// </summary>
        public static string ResetResources {
            get {
                return ResourceManager.GetString("ResetResources", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resources folder path.
        /// </summary>
        public static string ResourcesFolderPath {
            get {
                return ResourceManager.GetString("ResourcesFolderPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Example: C:\Program Files (x86)\Steam\steamapps\common\dota 2 beta\game\dota\resource.
        /// </summary>
        public static string ResourcesFolderPathTooltip {
            get {
                return ResourceManager.GetString("ResourcesFolderPathTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Retry download.
        /// </summary>
        public static string RetryDownload {
            get {
                return ResourceManager.GetString("RetryDownload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rubick cast backswing text format.
        /// </summary>
        public static string RubickCastBackswingTextFormat {
            get {
                return ResourceManager.GetString("RubickCastBackswingTextFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Example: &quot;Rubick backswing: {0}&quot; where {0} is the cast backswing on the spell stolen by Rubick..
        /// </summary>
        public static string RubickCastBackswingTooltip {
            get {
                return ResourceManager.GetString("RubickCastBackswingTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Dota 2 resources file. Example: &quot;C:\Program Files (x86)\Steam\steamapps\common\dota 2 beta\game\dota\resource&quot;.
        /// </summary>
        public static string SelectResourcesFolder {
            get {
                return ResourceManager.GetString("SelectResourcesFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Setup.
        /// </summary>
        public static string Setup {
            get {
                return ResourceManager.GetString("Setup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use custom color.
        /// </summary>
        public static string UseCustomColor {
            get {
                return ResourceManager.GetString("UseCustomColor", resourceCulture);
            }
        }
    }
}
