//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dota2AdvancedDescriptions.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "14.0.0.0")]
    public sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int CastPointsTableIndex {
            get {
                return ((int)(this["CastPointsTableIndex"]));
            }
            set {
                this["CastPointsTableIndex"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("//table")]
        public string CastPointsTableXPath {
            get {
                return ((string)(this["CastPointsTableXPath"]));
            }
            set {
                this["CastPointsTableXPath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("tr")]
        public string Tr {
            get {
                return ((string)(this["Tr"]));
            }
            set {
                this["Tr"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("td")]
        public string Td {
            get {
                return ((string)(this["Td"]));
            }
            set {
                this["Td"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("th")]
        public string Th {
            get {
                return ((string)(this["Th"]));
            }
            set {
                this["Th"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://dota2.gamepedia.com/Cast_animation/Cast_points_and_backswings?printable=ye" +
            "s")]
        public string CastPointsTableAddress {
            get {
                return ((string)(this["CastPointsTableAddress"]));
            }
            set {
                this["CastPointsTableAddress"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int TableIdIndex {
            get {
                return ((int)(this["TableIdIndex"]));
            }
            set {
                this["TableIdIndex"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\Program Files (x86)\\Steam\\steamapps\\common\\dota 2 beta\\game\\dota\\resource")]
        public string ResourcesFolderPath {
            get {
                return ((string)(this["ResourcesFolderPath"]));
            }
            set {
                this["ResourcesFolderPath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("DOTA_Tooltip_ability")]
        public string DotaResourceMatch {
            get {
                return ((string)(this["DotaResourceMatch"]));
            }
            set {
                this["DotaResourceMatch"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(" - ")]
        public string TableAbilityHeroSeparator {
            get {
                return ((string)(this["TableAbilityHeroSeparator"]));
            }
            set {
                this["TableAbilityHeroSeparator"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("npc_dota_hero_")]
        public string HeroNamePrefix {
            get {
                return ((string)(this["HeroNamePrefix"]));
            }
            set {
                this["HeroNamePrefix"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("DOTA_Tooltip_ability_")]
        public string AbilityResourcePrefix {
            get {
                return ((string)(this["AbilityResourcePrefix"]));
            }
            set {
                this["AbilityResourcePrefix"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("bio")]
        public string ExcludeFromHeroesNames {
            get {
                return ((string)(this["ExcludeFromHeroesNames"]));
            }
            set {
                this["ExcludeFromHeroesNames"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("dota_english.txt")]
        public string DefaultResourcesFileName {
            get {
                return ((string)(this["DefaultResourcesFileName"]));
            }
            set {
                this["DefaultResourcesFileName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("[english]")]
        public string ResourcesEnglishModifier {
            get {
                return ((string)(this["ResourcesEnglishModifier"]));
            }
            set {
                this["ResourcesEnglishModifier"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int ExtraTextPosition {
            get {
                return ((int)(this["ExtraTextPosition"]));
            }
            set {
                this["ExtraTextPosition"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("dota_english.txt")]
        public string SelectedResourcesFileName {
            get {
                return ((string)(this["SelectedResourcesFileName"]));
            }
            set {
                this["SelectedResourcesFileName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Cast point: {0}")]
        public string CastPointTextFormat {
            get {
                return ((string)(this["CastPointTextFormat"]));
            }
            set {
                this["CastPointTextFormat"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Cast backswing: {0}")]
        public string CastBackswingTextFormat {
            get {
                return ((string)(this["CastBackswingTextFormat"]));
            }
            set {
                this["CastBackswingTextFormat"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string RubickCastBackswingTextFormat {
            get {
                return ((string)(this["RubickCastBackswingTextFormat"]));
            }
            set {
                this["RubickCastBackswingTextFormat"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#FF11C3E4")]
        public string SelectedColor {
            get {
                return ((string)(this["SelectedColor"]));
            }
            set {
                this["SelectedColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool UseCustomColor {
            get {
                return ((bool)(this["UseCustomColor"]));
            }
            set {
                this["UseCustomColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("<font color=\\\"{0}\\\">{1}</font>")]
        public string FontColorFormat {
            get {
                return ((string)(this["FontColorFormat"]));
            }
            set {
                this["FontColorFormat"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("_Description")]
        public string DescriptionSuffix {
            get {
                return ((string)(this["DescriptionSuffix"]));
            }
            set {
                this["DescriptionSuffix"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("_Note")]
        public string NoteSuffix {
            get {
                return ((string)(this["NoteSuffix"]));
            }
            set {
                this["NoteSuffix"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("_Lore")]
        public string LoreSuffix {
            get {
                return ((string)(this["LoreSuffix"]));
            }
            set {
                this["LoreSuffix"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("-applaunch 570")]
        public string Dota2LaunchArguments {
            get {
                return ((string)(this["Dota2LaunchArguments"]));
            }
            set {
                this["Dota2LaunchArguments"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("..\\..\\..\\..\\..\\..\\")]
        public string SteamFolderLevel {
            get {
                return ((string)(this["SteamFolderLevel"]));
            }
            set {
                this["SteamFolderLevel"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Steam.exe")]
        public string SteamExe {
            get {
                return ((string)(this["SteamExe"]));
            }
            set {
                this["SteamExe"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool HideValuesIfEqualToZero {
            get {
                return ((bool)(this["HideValuesIfEqualToZero"]));
            }
            set {
                this["HideValuesIfEqualToZero"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Camp")]
        public string HtmlParsingIgnoreModifier {
            get {
                return ((string)(this["HtmlParsingIgnoreModifier"]));
            }
            set {
                this["HtmlParsingIgnoreModifier"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("npc_dota_neutral_")]
        public string NeutralNamePrefix {
            get {
                return ((string)(this["NeutralNamePrefix"]));
            }
            set {
                this["NeutralNamePrefix"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("npc_dota_")]
        public string OtherNamePrefix {
            get {
                return ((string)(this["OtherNamePrefix"]));
            }
            set {
                this["OtherNamePrefix"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool NewLineAfterText {
            get {
                return ((bool)(this["NewLineAfterText"]));
            }
            set {
                this["NewLineAfterText"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Doom backswing: {0}")]
        public string DoomCastBackswingTextFormat {
            get {
                return ((string)(this["DoomCastBackswingTextFormat"]));
            }
            set {
                this["DoomCastBackswingTextFormat"] = value;
            }
        }
    }
}
