//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dota2AdvancedDescriptions.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "14.0.0.0")]
    public sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2")]
        public int CastPointsTableIndex {
            get {
                return ((int)(this["CastPointsTableIndex"]));
            }
            set {
                this["CastPointsTableIndex"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("//table")]
        public string CastPointsTableXPath {
            get {
                return ((string)(this["CastPointsTableXPath"]));
            }
            set {
                this["CastPointsTableXPath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("tr")]
        public string Tr {
            get {
                return ((string)(this["Tr"]));
            }
            set {
                this["Tr"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("td")]
        public string Td {
            get {
                return ((string)(this["Td"]));
            }
            set {
                this["Td"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("th")]
        public string Th {
            get {
                return ((string)(this["Th"]));
            }
            set {
                this["Th"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://dota2.gamepedia.com/index.php?title=Cast_animation&printable=yes")]
        public string CastPointsTableAddress {
            get {
                return ((string)(this["CastPointsTableAddress"]));
            }
            set {
                this["CastPointsTableAddress"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int TableIdIndex {
            get {
                return ((int)(this["TableIdIndex"]));
            }
            set {
                this["TableIdIndex"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\Program Files (x86)\\Steam\\steamapps\\common\\dota 2 beta\\game\\dota\\resource")]
        public string ResourcesFolderPath {
            get {
                return ((string)(this["ResourcesFolderPath"]));
            }
            set {
                this["ResourcesFolderPath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("DOTA_Tooltip_ability")]
        public string DotaResourceMatch {
            get {
                return ((string)(this["DotaResourceMatch"]));
            }
            set {
                this["DotaResourceMatch"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(" - ")]
        public string TableAbilityHeroSeparator {
            get {
                return ((string)(this["TableAbilityHeroSeparator"]));
            }
            set {
                this["TableAbilityHeroSeparator"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("npc_dota_hero_")]
        public string HeroNamePrefix {
            get {
                return ((string)(this["HeroNamePrefix"]));
            }
            set {
                this["HeroNamePrefix"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("DOTA_Tooltip_ability_")]
        public string AbilityResourcePrefix {
            get {
                return ((string)(this["AbilityResourcePrefix"]));
            }
            set {
                this["AbilityResourcePrefix"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("bio")]
        public string ExcludeFromHeroesNames {
            get {
                return ((string)(this["ExcludeFromHeroesNames"]));
            }
            set {
                this["ExcludeFromHeroesNames"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("dota_english.txt")]
        public string DefaultResourcesFileName {
            get {
                return ((string)(this["DefaultResourcesFileName"]));
            }
            set {
                this["DefaultResourcesFileName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("[english]")]
        public string ResourcesEnglishModifier {
            get {
                return ((string)(this["ResourcesEnglishModifier"]));
            }
            set {
                this["ResourcesEnglishModifier"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int ExtraTextPosition {
            get {
                return ((int)(this["ExtraTextPosition"]));
            }
            set {
                this["ExtraTextPosition"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Cast point: {0}\\nCast backswing: {1}\\n")]
        public string ExtraTextFormat {
            get {
                return ((string)(this["ExtraTextFormat"]));
            }
            set {
                this["ExtraTextFormat"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("dota_english.txt")]
        public string SelectedResourcesFileName {
            get {
                return ((string)(this["SelectedResourcesFileName"]));
            }
            set {
                this["SelectedResourcesFileName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Cast point: {0}")]
        public string CastPointTextFormat {
            get {
                return ((string)(this["CastPointTextFormat"]));
            }
            set {
                this["CastPointTextFormat"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Cast backswing: {0}")]
        public string CastBackswingTextFormat {
            get {
                return ((string)(this["CastBackswingTextFormat"]));
            }
            set {
                this["CastBackswingTextFormat"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string RubickCastBackswingTextFormat {
            get {
                return ((string)(this["RubickCastBackswingTextFormat"]));
            }
            set {
                this["RubickCastBackswingTextFormat"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string SelectedColor {
            get {
                return ((string)(this["SelectedColor"]));
            }
            set {
                this["SelectedColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool UseCustomColor {
            get {
                return ((bool)(this["UseCustomColor"]));
            }
            set {
                this["UseCustomColor"] = value;
            }
        }
    }
}
